Controllers/GameController.cs
using FyraIRad.Models;
using Microsoft.AspNetCore.Mvc;

namespace FyraIRad.Controllers
{
    public class GameController : Controller
    {
        private readonly UserMethods userMethods;
        private readonly GameMethods gameMethods;
        private readonly MoveMethods moveMethods;
        private object currentUserId;

        public GameController(IConfiguration configuration)
        {
            userMethods = new UserMethods(configuration);
            gameMethods = new GameMethods(configuration);
            moveMethods = new MoveMethods(configuration);
        }
        //Starta spel, sätt spelstatus till waiting för att andra spelare ska kunna gå med
        [HttpPost]
        public IActionResult StartGame(int id)
        {
            GameDetails newGame = new GameDetails();

            newGame.playerRedId = (int)HttpContext.Session.GetInt32("UserId");
            newGame.playerYellowId = id;
            newGame.CurrentTurn = 'Y';
            newGame.Status = "Waiting";
            gameMethods.CreateGame(newGame);
            ViewBag.GameStatus = "Waiting";

            List<GameDetails> gameList = new List<GameDetails>();
            gameList = gameMethods.GetGameDetails(out string errormsg);
            newGame = gameList.Last();

           return RedirectToAction("ActiveGame", new { gameId = newGame.GameId });
           
        }
        //Joina spel. Kontroll att spelare kan joina, vilken spelare som joinar/startat spelet samt ändrar status till aktiv
        [HttpPost]
        public IActionResult JoinGame(int id)
        {
            List<GameDetails> gameList = new List<GameDetails>();
            gameList = gameMethods.GetGameDetails(out string errormsg);

            for (int i = 0; i < gameList.Count(); i++)
            {
                if ((gameList[i].playerRedId == id && gameList[i].playerYellowId == HttpContext.Session.GetInt32("UserId")) || (gameList[i].playerYellowId == id && gameList[i].playerRedId == HttpContext.Session.GetInt32("UserId")))
                {
                    if (gameList[i].Status == "Waiting" && gameList[i].playerYellowId == HttpContext.Session.GetInt32("UserId"))
                    {
                        gameList[i].Status = "Active";
                        
                    }
                    gameMethods.UpdateGameStatus(gameList[i]);

                    return RedirectToAction("ActiveGame", new { gameId = gameList[i].GameId });

                }
            }

            ViewBag.JoinError = "Could not find game to join";
            return RedirectToAction("ShowUserList", "LogIn");
        }
        //Aktiva spelet. Skickar data för spelare/färg, spelstatus, vinnare och gameID
        public IActionResult ActiveGame(int gameId)
        {
            GameDetails game = gameMethods.GetGameById(gameId, out string errormsg);

            if (game.Status != "Active")
            {
                ViewBag.MoveError = "Game not active";
            }
           
            ViewBag.GameStatus = game.Status;
            ViewBag.Winner = game.Winner;


            List<MoveDetails> moveList = moveMethods.GetMoveDetailsForGame(gameId, out string moveErr);
            ViewBag.MoveList = moveList;
            ViewBag.GameId = game.GameId;

            int currentUserID = (int)HttpContext.Session.GetInt32("UserId");

            List<UserDetails> allUsers = userMethods.GetUserDetails(out string userErr);

            UserDetails redPlayer = allUsers.FirstOrDefault(u => u.UserId == game.playerRedId);
            UserDetails yellowPlayer = allUsers.FirstOrDefault(u => u.UserId == game.playerYellowId);

            ViewBag.RedPlayerName = redPlayer != null ? redPlayer.Username : "Röd spelare";
            ViewBag.YellowPlayerName = yellowPlayer != null ? yellowPlayer.Username : "Gul spelare";
            ViewBag.CurrentTurn = game.CurrentTurn;

            return View(game);
        }
        //Skapa drag, tar in vilket spel samt vilken kolumn disken droppas i
        [HttpPost]
        public IActionResult CreateMove(int gameId, int column)
        {
            GameDetails currentGame = gameMethods.GetGameById(gameId, out string errormsg);

            char playerColor;

            // Kollar vilken färg spelaren har och sätter variabel till det
            if (currentGame.playerRedId == HttpContext.Session.GetInt32("UserId"))
            {
                playerColor = 'R';
            }
            else if (currentGame.playerYellowId == HttpContext.Session.GetInt32("UserId"))
            {
                playerColor = 'Y';
            }
            else
            {
                ViewBag.MoveError = "You are not a player in this game";
                return RedirectToAction("ActiveGame", new { gameId = currentGame.GameId });
            }
            // Kollar ifall det är den spelaren som försöker göra draget och lägger draget i newMove
            if (currentGame.CurrentTurn == playerColor && currentGame.Status == "Active")
            {
                MoveDetails newMove = new MoveDetails();
                newMove.GameId = gameId;
                newMove.ColumnIndex = column;

                List<MoveDetails> moveList = new List<MoveDetails>();
                moveList = moveMethods.GetMoveDetailsForGame(gameId, out string errorMsg);
                moveList = moveList.Where(m => m.ColumnIndex == column).ToList();

                int newRowIndex = 1;

               
                //Kontroll om en column är full

                if (moveList.Count() >= 6)
                {
                    ViewBag.MoveError = "Column is full, choose another column";
                    return RedirectToAction("ActiveGame", new { gameId = currentGame.GameId });
                }
                else if (moveList.Count() >= 1)
                {
                    newRowIndex = moveList.Min(m => m.RowIndex) - 1;
                }
                else
                {
                    newRowIndex = 6;
                }

                newMove.RowIndex = newRowIndex;

                //Lägger till spelare och färg baserat på vems tur det är till newMove

                if (currentGame.CurrentTurn == 'R')
                {
                    newMove.PlayerId = currentGame.playerRedId;
                    newMove.DiscColor = 'R';
                }
                else
                {
                    newMove.PlayerId = currentGame.playerYellowId;
                    newMove.DiscColor = 'Y';
                }
                moveMethods.CreateMove(newMove);
                // Switch turn
                if (currentGame.CurrentTurn == 'R')
                {
                    currentGame.CurrentTurn = 'Y';
                }
                else
                {
                    currentGame.CurrentTurn = 'R';
                }
                gameMethods.UpdateCurrentTurn(currentGame);

                // Tar in alla moves och skapar ett 7x6 bräde med moves för att kolla vinnare
                List<MoveDetails> allMoves = moveMethods.GetMoveDetailsForGame(gameId, out string allMovesErrorMsg);
                char[,] board = new char[7, 6];
                foreach (var move in allMoves)
                {
                    int row = move.RowIndex - 1;
                    int col = move.ColumnIndex - 1;
                    board[col, row] = move.DiscColor;
                }

                //Anropar checkwinner för att se om någon vunnit och uppdaterar spelet i så fall
                char winner = CheckWinner(board);
                if (winner == 'R' || winner == 'Y')
                {
                    // Mark game as finished, set winner
                    currentGame.Status = "Finished";
                    currentGame.Winner = winner;
                    gameMethods.UpdateGameStatus(currentGame);
                    gameMethods.UpdateWinner(currentGame);
                    return RedirectToAction("ActiveGame", new { gameId = currentGame.GameId });
                }

                // Kontroll om brädet är fullt för oavgjort
                bool isDraw = true;
                for (int c = 0; c < 7; c++)
                {
                    for (int r = 0; r < 6; r++)
                    {
                        if (board[c, r] == '\0')
                        {
                            isDraw = false;
                            break;
                        }
                    }
                    if (!isDraw) break;
                }

                // Om det är oavgjort, uppdatera spelet
                if (isDraw)
                {
                    currentGame.Status = "Draw";
                    currentGame.Winner = null;
                    gameMethods.UpdateGameStatus(currentGame);
                    gameMethods.UpdateWinner(currentGame);
                    return RedirectToAction("ActiveGame", new { gameId = currentGame.GameId });
                }

                return RedirectToAction("ActiveGame", new { gameId = currentGame.GameId });
            }
            else
            {
                ViewBag.MoveError = "It's not your turn";
                return RedirectToAction("ActiveGame", new { gameId = currentGame.GameId });
            }
        }
        [HttpPost]
        public IActionResult SurrenderGame(int gameId)
        {
        GameDetails game = gameMethods.GetGameById(gameId, out string errormsg);

        if (game != null)
            {
                // Om du vill markera som 'Surrendered' i databasen först (valfritt)
                game.Status = "Surrender";
                gameMethods.UpdateGameStatus(game);
                if (game.playerRedId == HttpContext.Session.GetInt32("UserId"))
                {
                    game.Winner = 'Y';
                }
                else if (game.playerYellowId == HttpContext.Session.GetInt32("UserId"))
                {
                    game.Winner = 'R';
                }
                gameMethods.UpdateWinner(game);

Controllers/LogInController.cs
using FyraIRad.Models;
using Microsoft.AspNetCore.Mvc;

namespace FyraIRad.Controllers
{
    public class LogInController : Controller
    {
        private readonly UserMethods userMethods;
        private readonly GameMethods gameMethods;

        public LogInController(IConfiguration configuration)
        {
            userMethods = new UserMethods(configuration);
            gameMethods = new GameMethods(configuration);
        }

        public IActionResult Index()
        {
            UserDetails user = new UserDetails();
            UserDetails newUser = new UserDetails();
            return View();
        }

        [HttpPost]
        public IActionResult LogIn(UserDetails tryLogin)
        {
            List<UserDetails> userList = new List<UserDetails>();

            userList = userMethods.GetUserDetails(out string errormsg);

            for (int i = 0; i < userList.Count; i++)
            {
                if (tryLogin.Username == userList[i].Username && tryLogin.Password == userList[i].Password)
                {
                    HttpContext.Session.SetInt32("UserId", (int)userList[i].UserId);
                    HttpContext.Session.SetString("Username", tryLogin.Username);
                    HttpContext.Session.SetString("Password", tryLogin.Password);
                    HttpContext.Session.SetString("IsLoggedIn", "true");

                    return RedirectToAction("ShowUserList");
                }
            }

            ViewBag.Error = "Username or password is incorrect";
            return View("Index");
        }

        [HttpPost]
        public IActionResult CreateUser(UserDetails newUser)
        {
            List<UserDetails> userList = new List<UserDetails>();

            userList = userMethods.GetUserDetails(out string errormsg);

            for (int i = 0; i < userList.Count; i++)
            {
                if (newUser.Username == userList[i].Username)
                {
                    ViewBag.Error = "Username already exists";
                    return View("Index");
                }
            }

            userMethods.CreateUser(newUser);

            return RedirectToAction("ShowUserList");
        }

        [HttpGet]
        public IActionResult ShowUserList()
        {
            if (HttpContext.Session.GetString("IsLoggedIn") == "true")
            {
                List<UserDetails> userList = new List<UserDetails>();

                userList = userMethods.GetUserDetails(out string errormsg);

                List<GameDetails> gameList = new List<GameDetails>();
                gameList = gameMethods.GetGameDetails(out string errorMsg);

                gameList = gameList.Where(g => (g.playerYellowId == HttpContext.Session.GetInt32("UserId") || g.playerRedId == HttpContext.Session.GetInt32("UserId"))).ToList();

                ViewBag.ActiveGames = gameList;

                for (int i = 0; i < userList.Count; i++)
                {
                    if (userList[i].UserId == HttpContext.Session.GetInt32("UserId"))
                    {
                        userList.RemoveAt(i);
                    }
                }

                return View(userList);
            }
            else
            {
                ViewBag.Error = "Not logged in";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult EditUser(int id)
        {
            if (HttpContext.Session.GetString("IsLoggedIn") == "true")
            {
                UserDetails user = new UserDetails();

                user = userMethods.GetOneUserDetails(id, out string errormsg);
                return View(user);
            }
            else
            {
                ViewBag.Error = "Not logged in";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult EditUser(UserDetails editUser)
        {
            userMethods.EditUser(editUser);
            HttpContext.Session.SetString("Username", editUser.Username);
            HttpContext.Session.SetString("Password", editUser.Password);
            return RedirectToAction("ShowUserList");
        }

        [HttpGet]
        public IActionResult DeleteUser(int id)
        {
            if (HttpContext.Session.GetString("IsLoggedIn") == "true")
            {
                UserDetails user = new UserDetails();
                user = userMethods.GetOneUserDetails(id, out string errormsg);
                return View(user);
            }
            else
            {
                ViewBag.Error = "Not logged in";
                return RedirectToAction("Index");
            }
        }

     [HttpPost]
public IActionResult DeleteUser(UserDetails deleteUser)
{
    userMethods.DeleteUser(deleteUser);
    HttpContext.Session.Clear(); // rensa session

    
    return RedirectToAction("Index", "LogIn");
}


        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "LogIn");
        }
    }
}

Views/LogIn/DeleteUser.cshtml
@model FyraIRad.Models.UserDetails

@{
    ViewData["Title"] = "DeleteUser";
}

<h1>Delete User</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Your User Details:</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="DeleteUser" method="post">
    <input type="hidden" name="UserId" value="@Model.UserId" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="ShowUserList">Back to List</a>
</form>
</div>

Views/LogIn/EditUser.cshtml
@model FyraIRad.Models.UserDetails

@{
    ViewData["Title"] = "EditUser";
}

<h1>Edit User</h1>

<h4>Your User Details:</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label">Id: </label>
                <input asp-for="UserId" type="hidden" />
                <p class="form-control-static">@Model.UserId</p>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowUserList">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/LogIn/Index.cshtml
@model FyraIRad.Models.UserDetails
@{
    ViewData["Title"] = "Log In";
}

<h1 class="mb-4"> <span class="text-danger">Welcome</span> <span class="text-success"> to the game of</span> <span class="text-primary">Fyra-I-Rad</span></h1>
<h4><span class="text-primary">Log In</span> <span class="text-success">or Create a </span> <span class="text-danger">New User</span></h4>

<hr />

@ViewBag.Error

<h5><span class="text-danger">Log In</span></h5>
<div class="row">
    <div class="col-md-4">
        <form asp-action="LogIn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="LogIn" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<br />
<br />
<h5><span class="text-danger">Create new User</span></h5>
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/LogIn/ShowUserList.cshtml
@model IEnumerable<FyraIRad.Models.UserDetails>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "ShowUserList";
    var activeGames = ViewBag.ActiveGames as List<FyraIRad.Models.GameDetails>;

}
<style>
    .btn-outline-warning.custom-hover {
        color: #ffc107; /* gul text som matchar kantfärgen */
        border-color: #ffc107;
    }

        .btn-outline-warning.custom-hover:hover {
            background-color: #ffc107;
            color: white; /* vit text vid hover */
        }
</style>


<h1><span class="text-success">Users List</span></h1>

@ViewBag.JoinError

<table class="table">
    <thead>

        <tr>
            <th><span class="text-danger">
                Users
                </span>
            </th>
            <th><span class="text-primary">
                Actions
                </span>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var hasActiveGame = activeGames?.Any(g => ((g.playerRedId == item.UserId) || (g.playerYellowId == item.UserId)) && (g.GameId != Accessor.HttpContext.Session.GetInt32("EndedGame"))) ?? false;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>

                @if (hasActiveGame)
                {
                    <td>
                        <form asp-action="JoinGame" asp-controller="Game" method="post">
                        <input type="hidden" name="id" value="@item.UserId" />
                        <button type="submit" class="btn btn-success">Join Game</button>
                    </form>
                    </td>
                }
                else
                {
                    <td>
                        <form asp-action="StartGame" asp-controller="Game" method="post">
                            <input type="hidden" name="id" value="@item.UserId" />
                            <button type="submit" class="btn btn-primary">Start Game</button>
                        </form>
                    </td>
                }

                
            </tr>
        }
    </tbody>
</table>

<div style="border: 1px solid black; padding: 10px;">
    <h5><span class="text-primary">Your User:</span></h5><span class="text-success">
    Id:</span> @Accessor.HttpContext.Session.GetInt32("UserId") <br />
    <span class="text-danger">Username:</span> @Accessor.HttpContext.Session.GetString("Username")
    
    <div class="mt-3">
        @Html.ActionLink("Edit", "EditUser", new { id = @Accessor.HttpContext.Session.GetInt32("UserId") }, new { @class = "btn btn-outline-primary btn-sm me-3" })
        @Html.ActionLink("Delete", "DeleteUser", new { id = @Accessor.HttpContext.Session.GetInt32("UserId") }, new { @class = "btn btn-outline-danger btn-sm me-3" })
        @Html.ActionLink("Logout", "Logout", "LogIn", null, new { @class = "btn btn-outline-warning custom-hover btn-sm me-3" })
    </div>
</div>